"""add attributes to offer

Revision ID: e1ec0390c3fb
Revises: ccd49673ae29
Create Date: 2026-04-16 13:17:11.931410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ec0390c3fb'
down_revision = 'ccd49673ae29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attributes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('attributes')

    # ### end Alembic commands ###
